
image: docker:latest


stages:
  - test_runner
  - build
  - deploy_stage
  - deploy_prod

variables:
  # Docker Hub erişim bilgileri
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "muratkorkmaz24/nodejs-express-mysql"
  HELM_CHART_DIR: "./helm-chart"  # Helm chart dosya yolu

  # Stage ortamı için Kubernetes bilgileri
  KUBE_CONTEXT_STAGE: "minikube"
  KUBE_NAMESPACE_STAGE: "nodejs-app-stage"
  ARGOCD_APP_NAME_STAGE: "nodejs-express-mysql"

  # Prod ortamı için Kubernetes bilgileri
  KUBE_CONTEXT_PROD: "minikube"
  KUBE_NAMESPACE_PROD: "nodejs-app"
  ARGOCD_APP_NAME_PROD: "nodejs-express-mysql-stage"

services:
  - name: docker:20.10.7-dind
    alias: docker

before_script:
  - docker info
  - apk add --no-cache curl bash
  - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - helm version
  - which helm
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/
  - kubectl version --client
  - mkdir -p ~/.kube
  - echo "$KUBECONFIG_FILE_CONTENT" | base64 -d > ~/.kube/config
  - kubectl config view

test_runner:
  stage: test_runner
  script:
    - echo "Testing GitLab Runner functionality"
    - echo "Running on $(hostname)"
    - docker --version
    - helm version
    - kubectl version --client
    - kubectl config view
    - kubectl get nodes --context $KUBE_CONTEXT_STAGE
    - echo "Runner test completed successfully!"
  only:
    - all  # Bu aşama tüm branch'ler için çalışır
# Build Docker image
build_image:
  stage: build
  script:
    - echo "Building Docker image"
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA .
    - echo "EbuA7Trqq!" | docker login -u "muratkorkmaz24" --password-stdin
    - docker images 
    - docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_REGISTRY/$DOCKER_IMAGE:latest
    - docker images
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - staging
    - main  # Hem staging hem de main branch'leri için geçerli


# Deploy to Kubernetes (Stage ortamı için)
deploy_stage:
  stage: deploy_stage
  script:
    - echo "Deploying to Kubernetes (Stage) using Helm"
    - helm upgrade --install nodejs-express-mysql-stage $HELM_CHART_DIR --namespace $KUBE_NAMESPACE_STAGE --set image.tag=$CI_COMMIT_SHA --context $KUBE_CONTEXT_STAGE
  only:
    - staging  # Sadece staging branch'inde çalışacak

# Deploy to Kubernetes (Prod ortamı için)
deploy_prod:
  stage: deploy_prod
  script:
    - kubectl config view
    - kubectl get nodes --context $KUBE_CONTEXT_PROD
    - echo "Deploying to Kubernetes (Prod) using Helm"
    - kubectl get nodes
    - helm upgrade --install nodejs-express-mysql $HELM_CHART_DIR --namespace $KUBE_NAMESPACE_PROD --set image.tag=$CI_COMMIT_SHA --context $KUBE_CONTEXT_PROD
  only:
    - main  # Sadece main branch'inde çalışacak
