apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/muratkorkmaz1/codeway-case-study.git'
    targetRevision: main
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nodejs-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
